version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env # Load .env file into the container
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Variabel diambil dari .env
      MYSQL_DATABASE: ${DB_NAME} # Variabel diambil dari .env
      MYSQL_USER: ${DB_USER} # Variabel diambil dari .env
      MYSQL_PASSWORD: ${DB_PASSWORD} # Variabel diambil dari .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
